### ISSUE TITLE
Comment out or delete icon element 

### ISSUE THREAD

**Issue by nburd90** [nburd90/crispy-couscous#10]
Comment out or delete icon element - #10

**Comment by nburd90** [comment]
This action was successful.

**Comment by nburd90** [comment]
Comment out or delete icon element - #10

**Comment by billythakidd04** [comment]
> Comment out or delete icon element - #10

@nburd90 #10 is _this_ issue ticket... what pull request or commit was responsible for the fix?

**Comment by nburd90** [comment]
Commit # - 1c0ee5e552dcc7716b0a436d1b0478fb72c3c699
