### ISSUE TITLE
Fix aboutUs banner image and navbar spacing and margins 

### ISSUE THREAD

**Issue by nburd90** [nburd90/crispy-couscous#24]
- Remove spacing to right of navbar. 
- May have something to do with banner image size and position.

**Comment by billythakidd04** [comment]
The way I read this, you should have at least 2 maybe 3 different tickets from this. You can leave this as the "parent" ticket and create smaller ones that relate to this. Or turn this into a milestone and then link those tickets to the milestone.

**Comment by nburd90** [comment]
Commit b25cc20

**Comment by billythakidd04** [comment]
@nburd90 if you just put "for #<ticket number>" in the commit message it will automatically tag to the relevant issue.
