### ISSUE TITLE
Images don't appear on page

### ISSUE THREAD

**Issue by nburd90** [nburd90/crispy-couscous#6]

**Comment by nburd90** [comment]
This issue has been fixed - style tag needed a ../ to properly link url to div image background.

**Comment by billythakidd04** [comment]
@nburd90 which commit or pr fixed this issue?

**Comment by nburd90** [comment]
I put a “..” before the / in background: url()

so url(../crispy-couscous/images/image).

However, when I load it through the server the images don’t show up but
when I dragged into a browser too so now have to figure that out.

**Comment by billythakidd04** [comment]
Ok so I'll reopen the ticket. Make sure you tag the pull request with this issue number once it's ready and add me as a reviewer.

**Comment by billythakidd04** [comment]
Reassigning to @WaymonBrown84. This should be relatively simple to fix. Let me know if you need help.

**Comment by billythakidd04** [comment]
@nburd90 was this fixed?
